### ISSUE TITLE
run cargo install will be an error

### ISSUE THREAD

**Issue by wulinsheng123** [HerringtonDarkholme/vue-compiler#274]
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/wuls/Desktop/rust/vue-compiler/crates/wasm/Cargo.toml
workspace: /Users/wuls/Desktop/rust/vue-compiler/Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/wuls/Desktop/rust/vue-compiler/napi/Cargo.toml
workspace: /Users/wuls/Desktop/rust/vue-compiler/Cargo.toml
error: found a virtual manifest at `/Users/wuls/Desktop/rust/vue-compiler/Cargo.toml` instead of a package manifest

I follow [this doc](https://github.com/HerringtonDarkholme/vue-compiler/blob/main/.github/CONTRIBUTING.md),
it will be an error

**Comment by HerringtonDarkholme** [comment]
Try cargo build instead

**Comment by wulinsheng123** [comment]
wuls@XD021NB2003146 crates % cargo build
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/wuls/Desktop/rust/vue-compiler/crates/wasm/Cargo.toml
workspace: /Users/wuls/Desktop/rust/vue-compiler/Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/wuls/Desktop/rust/vue-compiler/napi/Cargo.toml
workspace: /Users/wuls/Desktop/rust/vue-compiler/Cargo.toml
   Compiling vue-ref-transform v0.1.0 (/Users/wuls/Desktop/rust/vue-compiler/crates/ref_transform)
warning: function is never used: `is_start_of_statement`
  --> crates/sfc/src/rewrite_default.rs:26:4
   |
26 | fn is_start_of_statement(input: &str, pos: usize) -> bool {
   |    ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `vue-compiler-sfc` (lib) generated 1 warning
   Compiling vue-compiler-cli v0.1.0 (/Users/wuls/Desktop/rust/vue-compiler/crates/cli)
The following warnings were emitted during compilation:

warning: clang: error: no such file or directory: 'tree-sitter-javascript/src/parser.c'
warning: clang: error: no input files

error: failed to run custom build command for `vue-ref-transform v0.1.0 (/Users/wuls/Desktop/rust/vue-compiler/crates/ref_transform)`

Caused by:
  process didn't exit successfully: `/Users/wuls/Desktop/rust/vue-compiler/target/debug/build/vue-ref-transform-2b7ae479dd17cdb2/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-apple-darwin")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-I" "tree-sitter-javascript/src" "-Wall" "-Wextra" "-Wno-unused-parameter" "-Wno-trigraphs" "-o" "/Users/wuls/Desktop/rust/vue-compiler/target/debug/build/vue-ref-transform-0bc9a8bcee6b0e99/out/tree-sitter-javascript/src/parser.o" "-c" "tree-sitter-javascript/src/parser.c"
  cargo:warning=clang: error: no such file or directory: 'tree-sitter-javascript/src/parser.c'
  cargo:warning=clang: error: no input files
  exit status: 1

  --- stderr


  error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-I" "tree-sitter-javascript/src" "-Wall" "-Wextra" "-Wno-unused-parameter" "-Wno-trigraphs" "-o" "/Users/wuls/Desktop/rust/vue-compiler/target/debug/build/vue-ref-transform-0bc9a8bcee6b0e99/out/tree-sitter-javascript/src/parser.o" "-c" "tree-sitter-javascript/src/parser.c" with args "cc" did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
error: build failed
wuls@XD021NB2003146 crates % 

will be same error

**Comment by HerringtonDarkholme** [comment]
`git submodule update --recursive`

**Comment by wulinsheng123** [comment]
wuls@XD021NB2003146 vue-compiler % git submodule update --recursive
wuls@XD021NB2003146 vue-compiler % cargo build
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/wuls/Desktop/rust/vue-compiler/crates/wasm/Cargo.toml
workspace: /Users/wuls/Desktop/rust/vue-compiler/Cargo.toml
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /Users/wuls/Desktop/rust/vue-compiler/napi/Cargo.toml
workspace: /Users/wuls/Desktop/rust/vue-compiler/Cargo.toml
   Compiling vue-ref-transform v0.1.0 (/Users/wuls/Desktop/rust/vue-compiler/crates/ref_transform)
warning: function is never used: `is_start_of_statement`
  --> crates/sfc/src/rewrite_default.rs:26:4
   |
26 | fn is_start_of_statement(input: &str, pos: usize) -> bool {
   |    ^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: `vue-compiler-sfc` (lib) generated 1 warning
The following warnings were emitted during compilation:

warning: clang: error: no such file or directory: 'tree-sitter-javascript/src/parser.c'
warning: clang: error: no input files

error: failed to run custom build command for `vue-ref-transform v0.1.0 (/Users/wuls/Desktop/rust/vue-compiler/crates/ref_transform)`

Caused by:
  process didn't exit successfully: `/Users/wuls/Desktop/rust/vue-compiler/target/debug/build/vue-ref-transform-2b7ae479dd17cdb2/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-apple-darwin")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-apple-darwin")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  CC_x86_64-apple-darwin = None
  CC_x86_64_apple_darwin = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-apple-darwin = None
  CFLAGS_x86_64_apple_darwin = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("cmpxchg16b,fxsr,sse,sse2,sse3,ssse3")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-I" "tree-sitter-javascript/src" "-Wall" "-Wextra" "-Wno-unused-parameter" "-Wno-trigraphs" "-o" "/Users/wuls/Desktop/rust/vue-compiler/target/debug/build/vue-ref-transform-0bc9a8bcee6b0e99/out/tree-sitter-javascript/src/parser.o" "-c" "tree-sitter-javascript/src/parser.c"
  cargo:warning=clang: error: no such file or directory: 'tree-sitter-javascript/src/parser.c'
  cargo:warning=clang: error: no input files
  exit status: 1

  --- stderr


  error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-arch" "x86_64" "-I" "tree-sitter-javascript/src" "-Wall" "-Wextra" "-Wno-unused-parameter" "-Wno-trigraphs" "-o" "/Users/wuls/Desktop/rust/vue-compiler/target/debug/build/vue-ref-transform-0bc9a8bcee6b0e99/out/tree-sitter-javascript/src/parser.o" "-c" "tree-sitter-javascript/src/parser.c" with args "cc" did not execute successfully (status code exit status: 1).

I executed `git submodule update --recursive`,
but  still error

**Comment by HerringtonDarkholme** [comment]
```
git submodule init 
git submodule update --recursive
```

https://git-scm.com/book/en/v2/Git-Tools-Submodules#_cloning_submodules
