### ISSUE TITLE
run playground/"npm run build" throw an error

### ISSUE THREAD

**Issue by trueLoving** [HerringtonDarkholme/vue-compiler#60]
![documemts](https://user-images.githubusercontent.com/44056372/139566318-b254086f-1088-49f9-8030-0bea118a9ac8.png)

I follow the playground/README.md, use 'wasm-pack build' to build wasm,and then run "npm run build" in  playground directory.

it throw an error 

![error](https://user-images.githubusercontent.com/44056372/139566013-67ae0b29-f8a2-4767-aa73-fb852ff85666.png)

Then I use "wasm-build build --target web" to build wasm, run "npm run build" again find it's ok

![success](https://user-images.githubusercontent.com/44056372/139566069-a8b2fb13-55e8-40ac-bfb1-f8cf0f45b2f5.png)

**Comment by HerringtonDarkholme** [comment]
Hi! I think it's a document typo! We need to add --target web
