### ISSUE TITLE
can it remove the nightly features ? 

### ISSUE THREAD

**Issue by Stvchm9703** [HerringtonDarkholme/vue-compiler#648]
hi there, 
currently I am trying the file parsing part by directly importing the crate  `vue-compiler-core`. 
Is it possible to remove `once_cell` feature? or any advice for the replacement of once_cell?

sorry for my dumb asking, but I think it is not a good idea to build with the nightly feature

**Comment by HerringtonDarkholme** [comment]
Of course, with the release of new Rust we can use stable version.
