### ISSUE TITLE
vue-compiler-core problems

### ISSUE THREAD

**Issue by ssccchh** [HerringtonDarkholme/vue-compiler#825]
Why does the output ast structure have no child nodes when I parse the sfc with vue-compiler-core

```
use vue_compiler_core::{
    error::ErrorHandler,
    parser::{ParseOption, Parser},
    scanner::{ScanOption, Scanner, TextMode, TokenSource},
};

pub use vue_compiler_core::parser::AstRoot;
pub struct NoopErrorHandler;
impl ErrorHandler for NoopErrorHandler {}

fn scan_with_opt(s: &str, opt: ScanOption) -> impl TokenSource {
    let scanner = Scanner::new(opt);
    let ctx = NoopErrorHandler;
    scanner.scan(s, ctx)
}

pub fn base_scan(s: &str) -> impl TokenSource {
    scan_with_opt(s, ScanOption::default())
}

pub fn base_parse(s: &str) -> AstRoot {
    let tokens = base_scan(s);
    let parser = Parser::new(ParseOption {
        ..ParseOption::default()
    });
    let eh = NoopErrorHandler;
    parser.parse(tokens, eh)
}
```

will parse code
```
<script setup>
useHead({
  title: 'Nuxt Turbo App',
  link: [
    {
      rel: 'icon', type: 'image/png', href: '/images/nuxt.png',
    },
  ],
})
</script>

<template>
  <NuxtLayout>
    <NuxtPage></NuxtPage>
  </NuxtLayout>
</template>

<style>
html, body , #__nuxt{
  height: 100vh;
  margin: 0;
  padding: 0;
}

html.dark {
  background: #222;
  color: white;
}
</style>

```

parse result ast

![image](https://user-images.githubusercontent.com/26810503/231449602-02ce9993-a459-4e8c-92e3-dd7c6445508d.png)

**Comment by HerringtonDarkholme** [comment]
Hi, vue_compiler_core only handles template code instead of sfc.

To parse sfc you need to use vue_compiler_sfc. Please see https://github.com/HerringtonDarkholme/vue-compiler/blob/main/crates/cli/src/cli.rs for example.

**Comment by ssccchh** [comment]
But I did not find the crate of vue-complier-sfc in crate.io

**Comment by HerringtonDarkholme** [comment]
It's not completed yet. You should build it from source.

**Comment by ssccchh** [comment]
> It's not completed yet. You should build it from source.

ok

**Comment by ssccchh** [comment]
If I only want to manipulate the ast, is it currently impossible for the tool to do so because I find that the ast structure I get is always only one layer

**Comment by HerringtonDarkholme** [comment]
Sorry I don't know what you mean. 
You can write in your own native language and translate it via deepl.
If you are talking about parsing ast please see the cli example above.

This project has not been polished to be used by API users. Sponsoring the project might accelerate its development thoguh. https://github.com/sponsors/HerringtonDarkholme/

**Comment by ssccchh** [comment]
我现在想用您的工具来解析vue的模板部分，拿到ast结构来进行下一步操作，但是我发现我按照您给的例子实现之后，得到的ast结构还是只有一层，没有解析到子元素，我想知道目前您的工具除了直接编译生成render外，支持我直接去操作ast吗

**Comment by HerringtonDarkholme** [comment]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/2883231/231689484-2922e74c-ee41-415b-831a-86dd6a0a8b0d.png">

**Comment by ssccchh** [comment]
![image](https://user-images.githubusercontent.com/26810503/231689984-ef446b1c-5cb1-46c6-b559-9a09364be4af.png)
您看一下，这个是通过parse解析出来的ast

解析的源码：
```
<NuxtLayout>
    <NuxtPage></NuxtPage>
  </NuxtLayout>
```

**Comment by HerringtonDarkholme** [comment]
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/2883231/231691114-09cb5cc9-2050-4033-b792-6ce8bf85928d.png">

**Comment by ssccchh** [comment]
抱歉，是vscode调试工具的问题，打扰了
