### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by wre232114** [HerringtonDarkholme/vue-compiler#903]
Currently Farm (https://github.com/farm-fe/farm) is working on compiling Vue project in Rust(see https://github.com/farm-fe/farm/issues/125). If this project is not active, Farm is glad to develop this project, continue to make it production available

**Comment by HerringtonDarkholme** [comment]
Hi, I don't have enough capacity to support development recently. You can submit any pull request if you need to continue the project. 

I can do code review pretty fast.

**Comment by phoenix-ru** [comment]
@wre232114 I am also actively developing an alternative implementation of Vue compilation in Rust, however not production-ready yet, but with plugin support and native bundlers integration in mind: https://github.com/phoenix-ru/fervid

I base it off my usage and https://play.vuejs.org

**Comment by wre232114** [comment]
> @wre232114 I am also actively developing an alternative implementation of Vue compilation in Rust, however not production-ready yet, but with plugin support and native bundlers integration in mind: https://github.com/phoenix-ru/fervid
> 
> I base it off my usage and https://play.vuejs.org
> 
> upd. My project already uses SWC as its base, as is farm, so technically integration should be smooth (and I would like to try it)

That's amazing! I'll investigate it, maybe we can collaborate to speed up vue project compilation
