### ISSUE TITLE
Separate parser as a dedicated crate

### ISSUE THREAD

**Issue by g-plane** [HerringtonDarkholme/vue-compiler#960]
Currently Vue SFC parser is included in the "vue-compiler-core" crate. Would you like you separate and publish the parser as a crate? I hope it can only parser `<template>` section, while other sections like `<script>` and `<style>` are kept as source text, leaving them to user to decide how to process them.

**Comment by HerringtonDarkholme** [comment]
Hi, I think vue-compiler-core should satisfy your need? You can use tokenizer/parser to produce AST.

**Comment by g-plane** [comment]
It should satisfy, but actually I don't need codegen and other something else. Dropping those parts I don't need can reduce `target` directory size and compilation time. (rustc is slow, you know)

**Comment by HerringtonDarkholme** [comment]
You can try use the whole core crate and benchmarking how much it takes to compile. It is pretty fast and of minimal footprint.

**Comment by g-plane** [comment]
Maybe off-topic: Will there be an AST explorer for the parser?

**Comment by HerringtonDarkholme** [comment]
@g-plane vue compiler Rust currently has several dump options. https://github.com/HerringtonDarkholme/vue-compiler/blob/main/crates/cli/src/main.rs#L26-L46
Playground is not yet done now.

**Comment by g-plane** [comment]
I wish the AST types can derive from the `Debug` trait.
